create table if not exists public.remote_commands (
    id bigint generated by default as identity primary key,
    site_id text not null,
    tuya_device_id text null,
    action text not null check (action in ('on', 'off', 'test')),
    status text not null default 'pending' check (status in ('pending', 'processing', 'done', 'error')),
    device_name text null,
    local_key text null,
    lan_ip text null,
    version text null,
    result jsonb null,
    error_message text null,
    processor_site_id text null,
    claimed_at timestamptz null,
    executed_at timestamptz null,
    updated_at timestamptz not null default timezone('utc', now()),
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_remote_commands_site_status
    on public.remote_commands (site_id, status, created_at desc);

alter publication supabase_realtime add table public.remote_commands;

comment on table public.remote_commands is
'Fila de comandos remotos para o gateway local. O app escuta INSERTs via Supabase Realtime e executa ligar/desligar da placa ou teste remoto.';
